import { contextBridge, ipcRenderer } from 'electron';
import type { FactoryApi } from '../shared/contracts';
const names = [
  'dataMigrationState',
  'previewDataMigration',
  'confirmDataMigration',
  'discardDataMigration',
  'dataBackupState',
  'exportAppData',
  'previewDataRestore',
  'confirmDataRestore',
  'discardDataRestore',
  'appAiState',
  'grantAppAi',
  'revokeAppAi',
  'exportSource',
  'applicationState',
  'openApplication',
  'closeApplication',
  'runtimeState',
  'checkRuntime',
  'recoveryState',
  'restoreCheckpoint',
  'planState',
  'createPlan',
  'codingState',
  'codingFile',
  'generateSource',
  'buildState',
  'buildSource',
  'repairState',
  'repairSource',
  'openPreview',
  'closePreview',
  'blogStatus',
  'startBlog',
  'stopBlog',
  'snapshot',
  'createProject',
  'renameProject',
  'archiveProject',
  'saveRequirements',
  'approveRequirements',
  'generateRequirements',
  'generateDesign',
  'approveDesign',
  'saveProvider',
  'checkProvider',
  'deleteProviderKey',
  'cancelGeneration',
  'openDataFolder',
] as const;
const api = Object.fromEntries(
  names.map((name) => [
    name,
    (payload?: unknown) => ipcRenderer.invoke(`factory:${name}`, payload),
  ]),
) as unknown as FactoryApi;
contextBridge.exposeInMainWorld('factory', Object.freeze(api));
