import type { FactoryApi, ApiResult, AppSnapshot } from '../shared/contracts';

const unavailable = async <T>(): Promise<ApiResult<T>> => ({
  ok: false,
  error: {
    code: 'DESKTOP_REQUIRED',
    message: '这是浏览器界面预览。请在桌面工作台中创建项目、保存内容和连接模型。',
  },
});

const previewSnapshot: AppSnapshot = {
  projects: [],
  settings: {
    provider: 'deepseek',
    baseUrl: 'https://api.deepseek.com',
    model: 'deepseek-flash',
    hasKey: false,
    storage: 'none',
    lastCheckedAt: null,
    maxCalls: 30,
    maxTokens: null,
    budgetTokens: 0,
    legacyUnknownUsageCalls: 0,
    connectionId: '',
  },
  usage: { calls: 0, inputTokens: 0, outputTokens: 0, unknownUsageCalls: 0 },
  environment: {
    platform: '浏览器',
    arch: '—',
    version: '界面预览',
    dataPath: '仅桌面版可用',
    secureStorage: false,
    mode: 'browser-preview',
  },
};

const previewApi: FactoryApi = {
  workflowState: unavailable,
  runWorkflow: unavailable,
  gapReport: unavailable,
  recordGapEvidence: unavailable,
  dataMigrationState: unavailable,
  previewDataMigration: unavailable,
  confirmDataMigration: unavailable,
  discardDataMigration: unavailable,
  dataBackupState: unavailable,
  exportAppData: unavailable,
  previewDataRestore: unavailable,
  confirmDataRestore: unavailable,
  discardDataRestore: unavailable,
  appAiState: unavailable,
  grantAppAi: unavailable,
  revokeAppAi: unavailable,
  exportSource: unavailable,
  applicationState: unavailable,
  openApplication: unavailable,
  closeApplication: unavailable,
  runtimeState: unavailable,
  checkRuntime: unavailable,
  recoveryState: unavailable,
  restoreCheckpoint: unavailable,
  planState: unavailable,
  createPlan: unavailable,
  codingState: unavailable,
  codingFile: unavailable,
  generateSource: unavailable,
  repairState: unavailable,
  repairSource: unavailable,
  buildState: unavailable,
  buildSource: unavailable,
  openPreview: unavailable,
  closePreview: unavailable,
  blogStatus: unavailable,
  startBlog: unavailable,
  stopBlog: unavailable,
  snapshot: async () => ({ ok: true, value: structuredClone(previewSnapshot) }),
  createProject: unavailable,
  renameProject: unavailable,
  archiveProject: unavailable,
  saveRequirements: unavailable,
  approveRequirements: unavailable,
  generateRequirements: unavailable,
  generateDesign: unavailable,
  approveDesign: unavailable,
  saveProvider: unavailable,
  checkProvider: unavailable,
  deleteProviderKey: unavailable,
  cancelGeneration: unavailable,
  openDataFolder: unavailable,
};

export const api: FactoryApi = window.factory ?? previewApi;
