import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import {
  BLUEPRINT_COMPONENTS,
  BLUEPRINT_FEATURES,
  BLUEPRINT_SOURCE,
  selectBlueprintComponents,
  type BlueprintComponentDecision,
  type BlueprintFeatures,
  type BlueprintProfile,
} from '../src/main/blueprint-rules.js';
import { AppError } from '../src/main/validation.js';

// Expected outputs were generated by the pinned Python implementation, not by
// the TypeScript port. Running these tests needs neither Python nor a model.
const fixture = JSON.parse(
  readFileSync(new URL('./fixtures/blueprint-rules-parity.json', import.meta.url), 'utf8'),
) as {
  source: typeof BLUEPRINT_SOURCE;
  components: typeof BLUEPRINT_COMPONENTS;
  features: typeof BLUEPRINT_FEATURES;
  cases: {
    name: string;
    features: BlueprintFeatures;
    expected: BlueprintComponentDecision[];
  }[];
};

test('component and feature metadata match the pinned upstream snapshot', () => {
  assert.deepEqual(BLUEPRINT_SOURCE, fixture.source);
  assert.deepEqual(BLUEPRINT_COMPONENTS, fixture.components);
  assert.deepEqual(BLUEPRINT_FEATURES, fixture.features);
  assert.equal(BLUEPRINT_COMPONENTS.length, 17);
  assert.equal(BLUEPRINT_FEATURES.length, 14);
});

for (const item of fixture.cases) {
  test(`upstream Python parity: ${item.name}`, () => {
    assert.deepEqual(selectBlueprintComponents('agent', item.features), item.expected);
  });
}

test('ordinary Web explicitly excludes every Agent component from missing-feature scoring', () => {
  const features: BlueprintFeatures = Object.fromEntries(
    BLUEPRINT_FEATURES.map((feature) => [feature.id, { value: 'yes' }]),
  );
  const decisions = selectBlueprintComponents('web', features);
  assert.deepEqual(
    decisions.map((item) => item.id),
    BLUEPRINT_COMPONENTS.map((item) => item.id),
  );
  assert.ok(decisions.every((item) => item.decision === '不适用'));
  assert.ok(decisions.every((item) => item.reason.includes('不作为缺失项计分')));
  assert.equal(decisions.find((item) => item.id === 's01')?.decision, '不适用');
  assert.equal(decisions.find((item) => item.id === 's02')?.decision, '不适用');
  assert.equal(decisions.find((item) => item.id === 's15')?.decision, '不适用');
});

test('Agent selection needs explicit feature facts and does not infer them from evidence text', () => {
  const result = selectBlueprintComponents('agent', {
    scheduled: { evidence: '用户提到每小时定时运行，但没有结构化确认' },
  });
  assert.equal(result.filter((item) => item.decision === '待确认').length, 14);
  assert.equal(result.filter((item) => item.decision === '必选').length, 2);
  assert.equal(result.find((item) => item.id === 's12')?.decision, '待确认');
  assert.equal(result.find((item) => item.id === 's15')?.decision, '放弃');
});

test('selection does not mutate caller input or return shared result objects', () => {
  const features: BlueprintFeatures = {
    multi_step: { value: 'yes', evidence: '  已确认的进度需求  ' },
  };
  const before = structuredClone(features);
  const result = selectBlueprintComponents('agent', features);
  result[0]!.reason = 'caller mutation';
  result.splice(1, 4);
  assert.deepEqual(features, before);
  assert.equal(selectBlueprintComponents('agent', features).length, 17);
  assert.notEqual(selectBlueprintComponents('agent', features)[0]!.reason, 'caller mutation');
  assert.equal(
    selectBlueprintComponents('agent', features).find((item) => item.id === 's05')?.reason,
    '已确认的进度需求',
  );
});

test('rule metadata and provenance cannot be mutated by consumers', () => {
  assert.ok(Object.isFrozen(BLUEPRINT_SOURCE));
  assert.ok(Object.isFrozen(BLUEPRINT_SOURCE.files));
  assert.ok(Object.isFrozen(BLUEPRINT_COMPONENTS));
  assert.ok(Object.isFrozen(BLUEPRINT_FEATURES));
  assert.ok(BLUEPRINT_COMPONENTS.every((item) => Object.isFrozen(item)));
  assert.ok(BLUEPRINT_COMPONENTS.every((item) => Object.isFrozen(item.signals)));
  assert.ok(BLUEPRINT_FEATURES.every((item) => Object.isFrozen(item)));
});

test('unsupported profiles and malformed feature envelopes fail explicitly', () => {
  const invalid = (error: unknown) => error instanceof AppError && error.code === 'INVALID_INPUT';
  for (const profile of ['blog', '', null, undefined, 1]) {
    assert.throws(() => selectBlueprintComponents(profile as BlueprintProfile), invalid);
  }
  for (const features of [
    null,
    [],
    1,
    'features',
    { unknown_feature: { value: 'yes' } },
    { multi_step: null },
    { multi_step: [] },
    { multi_step: 'yes' },
    { multi_step: { value: 'yes', key: 'unsupported' } },
    { multi_step: { value: true } },
    { multi_step: { value: 'x'.repeat(41) } },
    { multi_step: { evidence: false } },
    { multi_step: { evidence: 'x'.repeat(8_001) } },
    { multi_step: { evidence: 'invalid\u0000text' } },
    Object.create({ multi_step: { value: 'yes' } }),
    JSON.parse('{"__proto__":{"value":"yes"}}'),
  ]) {
    assert.throws(() => selectBlueprintComponents('agent', features as BlueprintFeatures), invalid);
    assert.throws(() => selectBlueprintComponents('web', features as BlueprintFeatures), invalid);
  }
});
